name: todo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  easy_date_timeline: ^1.1.3

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  easy_localization: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/translations/
